language: node_js
node_js:
  - '5'
addons:
  code_climate:
    repo_token: 16a3b79a46e7ef65d62681ed92a5391ab325718979de98e1468448a6bf3edf62
branches:
  only:
    - '/^v[0-9]/'
services:
  - mongodb
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: >-
      OSq8B8kfvxocmjL58VJgQAIzfVEoyCvJINnOsK71zzjbrmwSvNBCxNOfJMigF6ylEB4N+8TBN+dmdRN7ufWwm7jKAy3Bom+vvQggTJvaCVwIm/w6HlPOI6nPeoUbZk7TehEdmqzIa7UIT/Qp2bUlF6gVeo0J4jxf03/FmtHa2n9rvIfaYOM1Y1Agi/3L02Id6l+Y4LF8WSP7cd3vP03SRkk9tVIiKN6qxm5ldSQdm7PWvmAH7mlzTl0uodQf7EcmVpzy6nB+REwxINltCNrn3ZJJi9IlU04hMrSN6ph2bntuOBPNh7jf4XIyfppRvk5ElUXb32AC3YKY2gJJ3+bwPUZyTeqKFV53RGr7+odCuKb2fi18CuCYrt6DSRDoNgAz94ZWp6jSP0oy4RTv4r7X8vWrUeVGuNx4JZJKiHjivuobQwH6JE0o5724XS9nQixdRFXN2iY7gs2wpyI8HIzjFyk+vS4M5lNKQphx40A5f8QWJ9HCfkwhQ6npRZWepj+b5TdJxjNmxp8icufOd4NQnjS8tA8bowqCIIPZWgP+ZTkTonAXn7PRQU+9bBUyEYYG6RX+6iQ1aFs3BpD311iHKIuoCMVpCiH3kMzbV7c1UgvP5xdMWzhZDRpw2z6LDu91HPAVIW4o6P5smzUnFcuf3MYW1EPY4ALo1Goxw4W7x4c=
  'on':
    tags: true
    branches: true
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
